---
lsb_release: "focal"
hashicorp_gpg_url: "https://apt.releases.hashicorp.com/gpg"
hashicorp_gpg_fingerprint: "E8A0 32E0 94D8 EB4E A189  D270 DA41 8C88 A321 9F7B" ## https://www.hashicorp.com/security
hashicorp_gpg_keyring: "/usr/share/keyrings/hashicorp-archive-keyring.gpg"